### ISSUE TITLE
Unexpected EOF archive error 

### ISSUE THREAD

**Issue by ebi0501** [SIlvaMFPedro/pyimagesearch#4]
Hello
I download the files but it gives "Unexpected end of archive" error!

**Comment by SIlvaMFPedro** [comment]
You should be able to clone the repository using this command:
git clone https://github.com/SIlvaMFPedro/pyimagesearch.git

**Comment by jzwerling** [comment]
Think I found the issue.  In the search-bing-api-dataset, a few of the image files have bad extensions, you can see them here:
https://github.com/SIlvaMFPedro/pyimagesearch/tree/master/search-bing-api-dataset/dataset/bulbasaur
There are a few of these directories for the other pokemon as well.  At least on windows, was not able to clone or download a zip of this repo.  
Solved this by forking, and manually correcting the file extensions.
